version: '3.8'

services:
  backend:
    container_name: backend

    image: resd/backend:${BACKEND_IMAGE_TAG} # deploy.sh에 있는 값 읽음

    ports:
      - 8081:8080

    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-default}
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_NAME: ${MONGO_INITDB_DATABASE:-mydatabase}
      DB_USER: ${MONGO_APP_USER}
      DB_PASSWORD: ${MONGO_APP_PASSWORD}
      APP_ANALYSIS_TEMP-DIR: /app/analysis_temp
      APP_ANALYSIS_OSV-SCANNER-CMD: /usr/local/bin/osv-scanner

    volumes:
      - analysis_data:/app/analysis_temp # 추가

    networks:
      - mcplink-network

  mongodb:
    container_name: mongodb

    image: mongo:6.0

    ports:
      - 0.0.0.0:27017:27017

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-mydatabase}

    volumes:
      - mongodb_data:/data/db

    networks:
      - mcplink-network


networks:
  mcplink-network:
    driver: bridge

volumes:
  mongodb_data:
