version: '3.8'

services:
  backend:
    container_name: backend

#    image: resd/backend:latest
    image: resd/backend:${BACKEND_IMAGE_TAG}

    ports:
      - 8081:8081

#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - /usr/bin/docker:/usr/bin/docker
#      - /home/ubuntu/jenkins-data:/var/jenkins_home
#      - /home/ubuntu/link:/home/ubuntu/link

    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-default}

    networks:
      - mcplink-network

networks:
  mcplink-network:
      driver: bridge
