version: '3.8'

services:
  backend:
    container_name: backend

    image: resd/backend:${BACKEND_IMAGE_TAG} # deploy.sh에 있는 값 읽음

    ports:
      - 8081:8080

    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-default}
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_NAME: ${MONGO_INITDB_DATABASE:-mydatabase}
      DB_USER: ${MONGO_APP_USER}
      DB_PASSWORD: ${MONGO_APP_PASSWORD}
      APP_ANALYSIS_TEMP_DIR: /app/analysis_temp
      APP_ANALYSIS_OSV_SCANNER_CMD: /usr/local/bin/osv-scanner

    volumes:
      - analysis_data:/app/analysis_temp

    networks:
      - mcplink-network

    depends_on:
      - mongodb
      - mysql

  mongodb:
    container_name: mongodb

    image: mongo:6.0

    ports:
      - ${MONGO_PORT}:27017

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-mydatabase}

    volumes:
      - mongodb_data:/data/db

    networks:
      - mcplink-network

  mysql:
    container_name: mysql
    image: mysql:8.0

    ports:
      - ${MYSQL_PORT}:3306

    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
    - mysql_data:/var/lib/mysql

    networks:
      - mcplink-network


networks:
  mcplink-network:
    driver: bridge

volumes:
  mongodb_data:
  analysis_data:
  mysql_data: