spring:
  application:
    name: mcplink

  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

  config:
    import: classpath:secret.yml

  data:
    mongodb:
      host: ${mongodb.host}
      port: ${mongodb.port}
      database: ${mongodb.database}
      username: ${mongodb.username}
      password: ${mongodb.password}

server:
  http2:
    enabled: true
  servlet:
    context-path: /api

app:
  analysis:
    temp-dir: /app/analysis_temp
#    temp-dir: "C:/ssafy/a201-gitlab"
    osv-scanner-cmd: /usr/local/bin/osv-scanner