spring:
  application:
    name: mcplink

  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

  config:
    import: classpath:secret.yml

  data:
    mongodb:
      host: ${mongodb.host}
      port: ${mongodb.port}
      database: ${mongodb.database}
      username: ${mongodb.username}
      password: ${mongodb.password}

  datasource:
    jdbc-url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.database}?serverTimezone=Asia/Seoul
    username: ${mysql.user}
    password: ${mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  github:
    token: ${github.token}

server:
  http2:
    enabled: true
  servlet:
    context-path: /api

app:
  analysis:
    temp-dir: /app/analysis_temp
#    temp-dir: "C:/ssafy/a201-gitlab"
    osv-scanner-cmd: osv-scanner
#    osv-scanner-cmd: /usr/local/bin/osv-scanner