spring:
  application:
    name: mcplink

  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

  config:
    import: classpath:secret.yml

  data:
    mongodb:
      host: ${mongodb.host}
      port: ${mongodb.port}
      database: ${mongodb.database}
      username: ${mongodb.username}
      password: ${mongodb.password}